hash-format = "sha256"

[[files]]
file = "mods/ExRollerCoaster-1.5.1.jar"
hash = "ccbfa6d2b20f2cb7ac98a5c90b40346d34ea8b1a7d8453fb7773cbdd1442e9e7"

[[files]]
file = "mods/ae2-extended-life.pw.toml"
hash = "21d6ef9d52551f2adb9aad7752b551312fe417a693a992aee1dd0fbd83cce3d0"
metafile = true

[[files]]
file = "mods/alfheim-lighting-engine.pw.toml"
hash = "5b8e138b7b21ad18dd6ebdbf6cc4b23c2d2137a7253fd968a4030487c5fb9a28"
metafile = true

[[files]]
file = "mods/celeritas.pw.toml"
hash = "f616116ffe4d7adaac7e7cc6d61f894d9b10c6c2a691c4af8e6105a0cf553fe8"
metafile = true

[[files]]
file = "mods/configanytime.pw.toml"
hash = "defd8d7b171bb90e9ae3cc60f8c5e863346f74f7c43d90fd2a1519cc9b0e7f5f"
metafile = true

[[files]]
file = "mods/fugue.pw.toml"
hash = "01049ff49ed04e4f37d82babf97aed5c61e4fd1103b114c762e9eac1ec91ea3e"
metafile = true

[[files]]
file = "mods/galacticraft-legacy.pw.toml"
hash = "49fb6c7b176a6753ac1ffa2039042430d40659ddf0b22f59fec84380f5305276"
metafile = true

[[files]]
file = "mods/gnetum.pw.toml"
hash = "45a1cd557aadf621b6c76f39bc3659785d4a0905423ed0524865bc31c52272cb"
metafile = true

[[files]]
file = "mods/had-enough-items.pw.toml"
hash = "6ad7cc934e5cfc761dc738a6ec01a8388e645ffa50ad70837c01bc25f345eaed"
metafile = true

[[files]]
file = "mods/hwyla.pw.toml"
hash = "73ee822f3d0a45a96668ba4a11ef48a31337c2db7b94498f5c8cb1bc1c9acb1a"
metafile = true

[[files]]
file = "mods/lolasm.pw.toml"
hash = "dfa9635d3ca751b625ccc004a3c78e915954997f741576d58db3c5493286e764"
metafile = true

[[files]]
file = "mods/mcgltf.pw.toml"
hash = "b0e7fd5304ae9bf8016337cd22daa9d9faf32088cce53e6ab1ec2f27a8b52a68"
metafile = true

[[files]]
file = "mods/mixin-booter.pw.toml"
hash = "ad355300f200ceabaa960dcef945cdf94195f8944dbe42ada2db41e153f209dc"
metafile = true

[[files]]
file = "mods/modularwarfare.pw.toml"
hash = "7f18ca6496a86be2fae4052e8b6125596bf9372c35e610f08b5228668a67c669"
metafile = true

[[files]]
file = "mods/ntm-extended.pw.toml"
hash = "d301b752a47647ed1caeca9b79eceec14468a863af92b0711457950a0a830f8e"
metafile = true

[[files]]
file = "mods/paintings.pw.toml"
hash = "074b5fdf2ac37743bce1e5b562755340cc960db301522f5b374ccf91a508079e"
metafile = true

[[files]]
file = "mods/red-core.pw.toml"
hash = "06969f488405c789e0312c1a09be5e51bda6eab1d7869ab934cb55289aad3860"
metafile = true

[[files]]
file = "mods/scalar-legacy.pw.toml"
hash = "c1fb189ad08a9630c596e8609f90f2a7f7a19eb6a0bfdbb4841bd7c6a477e4fc"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "32f6af6a85906716c472a1187f341977fe80ca07391f5e486f0e80a64864435b"
metafile = true

[[files]]
file = "mods/stellarcore.pw.toml"
hash = "fa9df380bba4f7a73750b16021099e343e34cdd14cd983d570603718a1c4a501"
metafile = true

[[files]]
file = "mods/universal-tweaks.pw.toml"
hash = "bac5bb4b388e2e2102d0b2bc8fc103b524e41613b3a76a6e97fc8e91609f2257"
metafile = true

[[files]]
file = "mods/vintagefix.pw.toml"
hash = "21e1e9cb5ed51d3a6905304f1ba12fbecd3a009929a0ee474ceff11c9591b396"
metafile = true

[[files]]
file = "mods/xaerolib.pw.toml"
hash = "1ddf11283def3841f5c060d383594d99b1fa939daa228a9a2376f3a6f39fd87e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "de59749846dc0d12fa1a4795c06d77ab8d9f8c420c879edc77dff2715a3b8a63"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "e90cda6592408dd219103025fc1a2470059554368e9fb89001239eb7e39a2556"
metafile = true

[[files]]
file = "mods/xp-orb-clump.pw.toml"
hash = "4bf4bf8f2a8119733bdd21e3f0aeaa178aba9720e5fef0e4f65ec85e5dcb5884"
metafile = true

[[files]]
file = "update.sh"
hash = "ef382bb473dee1a973dae9e618ac2f188decd1e8c3f99ab4d1dc1a5476fc564a"
