name = "Industrial Dawn"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c457437b05ae5e0404f6ee215397cf02860aa4743e3db0de4a7ca4b2b39687"

[versions]
forge = "0.3.34-alpha"
minecraft = "1.12.2"

[options]
no-internal-hashes = false
