name = "Industrial Dawn"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477a15b5b23ae6695c28f6ee8300755942801e9d5ea97aecb98990009e601dd1"

[versions]
forge = "0.3.34-alpha"
minecraft = "1.12.2"

[options]
no-internal-hashes = false
