name = "Industrial Dawn"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4c076ee421277ea9bf0eda572422680a0f3cc0ad7adcf034862f7da38ffb3f"

[versions]
forge = "0.3.34-alpha"
minecraft = "1.12.2"

[options]
no-internal-hashes = false
