name = "Industrial Dawn"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "921e24f83ec62fb4a5151bb6cc480ae4070f093d6667be1cd19a05ae0924b32d"

[versions]
forge = "0.3.34-alpha"
minecraft = "1.12.2"

[options]
no-internal-hashes = false
