name = "Industrial Dawn"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cadeef49f024af076ab34316f64ffb3e048b571f68f6e5baea8004d3c848d8c"

[versions]
forge = "0.3.34-alpha"
minecraft = "1.12.2"

[options]
no-internal-hashes = false
